### ISSUE TITLE
Can't change Local Repository. Seems hard-coded?

### ISSUE THREAD

**Issue by qazip** [appml/neutrinote#19]
I am using latest version on F-Droid. Android 10.

I am trying to change the Local Repository to a folder of "my own" that I keep synced via Syncthing. However, after clicking "Local Repository Path" in the settings, there is only a pop-up showing me the current Local Repository Path. It is impossible to change it. Is this how it's supposed to be?

**Comment by appml** [comment]
> I am using latest version on F-Droid. Android 10.
> 
> I am trying to change the Local Repository to a folder of "my own" that I keep synced via Syncthing. However, after clicking "Local Repository Path" in the settings, there is only a pop-up showing me the current Local Repository Path. It is impossible to change it. Is this how it's supposed to be?

This is due to the compliance of app specific folder as recommended [here](https://developer.android.com/training/data-storage/app-specific) for protecting privacy in more recent Android.  Consider setting up a [mirror](https://appml.github.io/nano/) for the Local Repository and point to it from Syncthing since mirror is accessible to 3rd party apps.

Hope this helps.

**Comment by SIRSteiner** [comment]
But there is a problem if you don't set the path at the first start. Then you are not able to set it in settings.

**Comment by appml** [comment]
> But there is a problem if you don't set the path at the first start. Then you are not able to set it in settings. The only way is to remove the right for accessing storage. Then the app starts with the same dialog like the first start.

This is due to changing local repository could corrupt note data.   Please use the steps below to change its path:

https://appml.github.io/nano/#relocate

Also see Android's policy on file access:

https://developer.android.com/training/data-storage/app-specific

Alternatively, mirror is recommended for newer devices. 

https://appml.github.io/nano/#mirror

Thanks.

**Comment by appml** [comment]
Android system restrictions.

**Comment by appml** [comment]
> How to share the repo between the main profile and its private space ?

Local repo access no longer permitted by recent Android versions for security reasons.

Use [mirror](https://appml.github.io/nano/#mirror) for 3rd party sync instead.

**Comment by sterno900** [comment]
> > How to share the repo between the main profile and its private space ?
> 
> Local repo access no longer permitted by recent Android versions for security reasons.
> 
> Use [mirror](https://appml.github.io/nano/#mirror) for 3rd party sync instead.

yes im using mirror sync, but I would like to sync it to the same app located in my private space (android 16).
in quillpad it is possible, and shown as `16@com.android.externalstorage.documents: Mynotes/myfolder` and 16 being the profile number.
Its buggy in Neutrinote...
