### ISSUE TITLE
Single-file search??? (feature request)

### ISSUE THREAD

**Issue by Gabr-F** [appml/neutrinote#29]
Hello, is there really no way to search only in the currently open file??? Your search functionality might be blazing fast at searching everything at once, but if when you have to search something you need to go back to the files' list, find the file you were already in among the results and then, by the way (separate issue, #30) scroll through the entire file on the look for highlighted parts (rather than having a search next/previous feature as about any search thing has),  you lose a lot more time than with a slow single-file search feature...

And by the way is it me or the app did use to have this feature??? (back when I put so much stuff in it that it's now complex to switch to another)

**Comment by appml** [comment]
1. Conduct local search by clicking the search icon in the edit screen toolbar.
2. Once search finish, you can keep tapping the search button to go to the next result.  Or at any point while the search is active, click the search icon in edit toolbar to navigate among search results, or through the use of [gestures](https://appml.github.io/nano/#gestures).

Closing since this has already been documented.

**Comment by Gabr-F** [comment]
> 1. Conduct local search by clicking the search icon in the edit screen toolbar.

As I mentioned I did indeed seem to remember that there used to be a search icon in the edit screen, but I've been unable to see any for several versions (maybe even since January)!
Are you sure that it's still working?

I attach a screenshot of what I see:


I've been using the f-droid version by the way, now at 1.4.3.

**Comment by Gabr-F** [comment]
Ok trying other things I found out that the button bar is scrollable and there sits the search icon (among a smorgasbord of other things I wasn't aware of).

Closing the issue was correct.

However maybe the fact that the bar is scrollable needs better visual hints, or documentation?
